In [107]:
import numpy as np
import pandas as pd

In [108]:
df = pd.read_csv('grad_frame_2.csv')

In [109]:
df

        orig_index  token_id  attribution_score  label  prediction_prob
0           130859        35           0.115245    0.0         0.009886
1           130859        39           0.076365    0.0         0.009886
2           130859        44          -0.140192    0.0         0.009886
3           130859        55           0.146613    0.0         0.009886
4           130859        28          -0.124811    0.0         0.009886
...            ...       ...                ...    ...              ...
480782       56820        33          -0.533075    0.0         0.007491
480783       56820        31          -0.018007    0.0         0.007491
480784       56820        29          -0.233608    0.0         0.007491
480785       56820        28          -0.080859    0.0         0.007491
480786       56820        25           0.037460    0.0         0.007491

[480787 rows x 5 columns]

In [110]:
df['label'].value_counts()

label
0.0    470648
1.0     10139
Name: count, dtype: int64

In [111]:
pred_95 = df['prediction_prob'].quantile(0.9)

In [112]:
sort_95 = df.loc[df['prediction_prob']>pred_95].sort_values('prediction_prob', ascending=False)

In [113]:
top_25 = sort_95[['orig_index','label','prediction_prob']].drop_duplicates()[:20]['orig_index']

In [120]:
sort_95[['orig_index','label','prediction_prob']].drop_duplicates()[:30]

        orig_index  label  prediction_prob
39372        71240    0.0         0.522660
386494       60693    0.0         0.514146
403835      121293    0.0         0.493524
341274       22521    0.0         0.425588
407226       91751    0.0         0.397398
36132        43140    0.0         0.377007
241477       48993    0.0         0.360979
372788       38909    0.0         0.358583
415904      196822    1.0         0.353081
417546       98157    0.0         0.350793
339440      139642    0.0         0.349246
377431      120204    0.0         0.343121
319237       69640    0.0         0.339613
179069      107616    0.0         0.337975
267766      124717    0.0         0.328251
453465      178489    1.0         0.322500
318458       80883    0.0         0.315186
72845       130683    0.0         0.314015
446173       30999    1.0         0.310133
446583      141608    0.0         0.305816
421529      146020    0.0         0.303217
204517       28457    0.0         0.301360
389284       45680    0.0         0.301040
436397      127760    0.0         0.299104
312572      123130    1.0         0.296784
120530       87929    1.0         0.296672
302917      154634    0.0         0.296414
300478      193223    0.0         0.295578
177552         868    1.0         0.290375
201755      142957    0.0         0.284587

In [114]:
top_25

39372      71240
386494     60693
403835    121293
341274     22521
407226     91751
36132      43140
241477     48993
372788     38909
415904    196822
417546     98157
339440    139642
377431    120204
319237     69640
179069    107616
267766    124717
453465    178489
318458     80883
72845     130683
446173     30999
446583    141608
Name: orig_index, dtype: int64

# Discards

In [121]:
mahjong_tiles = [
    # Manzu (Characters)
    "1m", "2m", "3m", "4m", "5m", "6m", "7m", "8m", "9m",
    
    # Souzu (Bamboos)
    "1s", "2s", "3s", "4s", "5s", "6s", "7s", "8s", "9s",
    
    # Pinzu (Circles)
    "1p", "2p", "3p", "4p", "5p", "6p", "7p", "8p", "9p",
    
    # Winds
    "East", "South", "West", "North",
    
    # Dragons (Colors)
    "White", "Green", "Red"
]

In [122]:
wind_translate = {0:"East",1:"South",2:"West",3:"North"}
is_riichi_translate={0:"No",1:"Yes"}

In [123]:
df['token_id'] = df['token_id'].astype(int)

In [124]:
def display_discards(discard_df):
    print(f'Hand number: {discard_df['orig_index'][0]}')

    wind = discard_df['token_id'][0] - 34
    
    print(f'Wind: {wind}, {round(discard_df['attribution_score'][0],4)}')

    seat = discard_df['token_id'][1] - 38
    
    print(f'Seat: {seat}, {round(discard_df['attribution_score'][1],4)}')
    
    is_riichi = discard_df['token_id'][2] - 44
    
    print(f'Is riichi: {is_riichi_translate[is_riichi]}, {round(discard_df['attribution_score'][2],4)}')

    dora_ind = discard_df['token_id'][3] - 46
    
    print(f'Dora Indicator: {mahjong_tiles[dora_ind]}, {round(discard_df['attribution_score'][3],4)}')
    
    for i, r in discard_df[4:].iterrows():
        print(f'{mahjong_tiles[int(r['token_id'])]}, {round(r['attribution_score'],4)}')
    print('---------------------------------------------')

In [127]:
def display_discards_no_grad(discard_df):
    print(f'Hand number: {discard_df['orig_index'][0]}')

    wind = discard_df['token_id'][0] - 34
    
    print(f'Wind: {wind}')

    seat = discard_df['token_id'][1] - 38
    
    print(f'Seat: {seat}')
    
    is_riichi = discard_df['token_id'][2] - 44
    
    print(f'Is riichi: {is_riichi_translate[is_riichi]}')

    dora_ind = discard_df['token_id'][3] - 46
    
    print(f'Dora Indicator: {mahjong_tiles[dora_ind]}')
    
    for i, r in discard_df[4:].iterrows():
        print(f'{mahjong_tiles[int(r['token_id'])]}')
    print('---------------------------------------------')

In [128]:
for hand in top_25:
    display_discards_no_grad(df.loc[df['orig_index'] == hand].copy().reset_index())

Hand number: 71240
Wind: 1
Seat: 3
Is riichi: Yes
Dora Indicator: South
1p
Red
1s
Green
8p
Green
4p
North
8p
4m
6m
4p
8m
5s
5m
South
6m
---------------------------------------------
Hand number: 60693
Wind: 1
Seat: 0
Is riichi: No
Dora Indicator: 5p
Green
9m
1s
4m
3m
1p
7p
3m
5p
3p
9s
8p
9m
5m
6s
2p
4s
---------------------------------------------
Hand number: 121293
Wind: 1
Seat: 1
Is riichi: Yes
Dora Indicator: White
8s
5s
7p
8p
6m
4m
4m
8p
5m
8m
3m
7m
5p
West
West
Red
---------------------------------------------
Hand number: 22521
Wind: 1
Seat: 3
Is riichi: No
Dora Indicator: 1s
9p
4p
7p
4m
7m
9p
7m
4p
East
White
7p
Green
4m
2p
---------------------------------------------
Hand number: 91751
Wind: 1
Seat: 0
Is riichi: No
Dora Indicator: 8p
9m
6m
4m
6m
5m
4m
5s
East
4m
West
5m
7s
8s
3p
4m
---------------------------------------------
Hand number: 43140
Wind: 1
Seat: 0
Is riichi: No
Dora Indicator: South
9p
8s
1p
3p
East
5s
2s
North
2p
4s
5p
3s
6m
6p
Green
4m
7m
---------------------------------------------
Hand number: 48993
Wind: 0
Seat: 3
Is riichi: No
Dora Indicator: 7s
2s
6m
6m
4s
3m
3p
6m
4p
South
5s
South
West
5s
Red
White
White
---------------------------------------------
Hand number: 38909
Wind: 0
Seat: 0
Is riichi: No
Dora Indicator: 9s
8s
7m
4m
6s
2s
7s
White
1s
West
1p
5m
8p
3p
3p
8m
1s
South
---------------------------------------------
Hand number: 196822
Wind: 0
Seat: 0
Is riichi: No
Dora Indicator: East
1s
9m
9s
4m
East
1p
1p
7s
5p
4s
6s
8m
5p
8s
6m
East
7m
---------------------------------------------
Hand number: 98157
Wind: 0
Seat: 1
Is riichi: No
Dora Indicator: 1m
4p
8p
9p
6m
6m
8p
5s
6m
1p
6s
6m
5s
1s
1s
---------------------------------------------
Hand number: 139642
Wind: 1
Seat: 1
Is riichi: No
Dora Indicator: 8m
6m
5p
4s
4m
White
Green
7p
7p
5p
7s
9s
East
2s
5p
---------------------------------------------
Hand number: 120204
Wind: 1
Seat: 0
Is riichi: No
Dora Indicator: West
8m
5m
5m
6s
8s
8s
3s
5p
7s
1m
3m
2p
4m
4m
---------------------------------------------
Hand number: 69640
Wind: 1
Seat: 2
Is riichi: No
Dora Indicator: 5s
Green
3m
6m
North
8m
4m
9p
East
6p
5m
4p
3p
1s
1s
5p
---------------------------------------------
Hand number: 107616
Wind: 0
Seat: 1
Is riichi: No
Dora Indicator: 1s
2p
7p
2m
5m
7p
South
Green
8m
9s
4p
2s
Red
6s
6s
3m
6p
---------------------------------------------
Hand number: 124717
Wind: 0
Seat: 1
Is riichi: No
Dora Indicator: Red
9m
East
4m
3m
5s
3m
6p
2s
4s
5m
West
5m
6s
8s
South
West
7s
West
---------------------------------------------
Hand number: 178489
Wind: 0
Seat: 1
Is riichi: No
Dora Indicator: 9m
West
8p
4m
6m
4m
East
East
4p
8m
5s
5s
7p
5m
4m
4s
---------------------------------------------
Hand number: 80883
Wind: 2
Seat: 0
Is riichi: No
Dora Indicator: 6p
East
6m
3m
3p
5p
South
8m
7m
3s
5s
4s
8p
3s
3m
6m
---------------------------------------------
Hand number: 130683
Wind: 1
Seat: 0
Is riichi: No
Dora Indicator: 9s
Green
6m
6m
1m
5p
5p
6p
3s
6s
8m
North
7m
3s
---------------------------------------------
Hand number: 30999
Wind: 1
Seat: 0
Is riichi: No
Dora Indicator: 1p
1s
Red
South
3p
South
7p
1p
9s
Green
White
3m
6s
3m
4m
7m
---------------------------------------------
Hand number: 141608
Wind: 1
Seat: 2
Is riichi: Yes
Dora Indicator: 1p
9m
9p
1p
5p
6m
Green
White
6m
Red
1m
South
East
6m
4m
6s
---------------------------------------------

In [ ]:
for hand in top_25:
    display(df.loc[df['orig_index'] == hand].copy().reset_index())