In [60]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [51]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 300)

In [79]:
df = pd.read_csv('run_4_27_2025/grad_frame_10_layer.csv')

In [80]:
df = df.drop(df.loc[df['token_id']==0].index)

In [81]:
df['token_id']=df['token_id'].astype(str)

In [82]:
df.head(20)

    orig_index token_id  attribution_score  label  prediction_prob
0        20453        1          -0.304067    0.0         0.084188
1        20453       24          -6.350651    0.0         0.084188
2        20453        2          -1.930850    0.0         0.084188
3        20453       25           0.176169    0.0         0.084188
4        20453        4          -0.272070    0.0         0.084188
5        20453        5          -0.133688    0.0         0.084188
6        20453       63          -0.099698    0.0         0.084188
7        20453       78           0.302127    0.0         0.084188
8        20453       27           4.058901    0.0         0.084188
9        20453       36          -0.017207    0.0         0.084188
10       20453       58           0.526549    0.0         0.084188
11       20453       60           1.848001    0.0         0.084188
12       20453       78          -0.018339    0.0         0.084188
13       20453       77          -0.196443    0.0         0.084188
14       20453       21           0.290272    0.0         0.084188
15       20453       60           0.056206    0.0         0.084188
16       20453       14           0.273012    0.0         0.084188
17       20453       71          -0.484654    0.0         0.084188
18       20453       30          -0.227064    0.0         0.084188
19       20453       37          -0.064633    0.0         0.084188

In [83]:
df['label'].value_counts()

label
0.0    1124916
1.0      79857
Name: count, dtype: int64

In [84]:
with open('vocab/id2token.json', 'r') as file:
    id2token = json.load(file)

with open('vocab/token2id.json', 'r') as file:
    token2id = json.load(file)

In [85]:
def encode(seq, *, mapping=token2id, unk_token="<UNK>"):
    """Convert list[str] -> list[int]."""
    unk = mapping[unk_token]
    return [mapping.get(tok, unk) for tok in seq]

def decode(id_seq, *, reverse_mapping=id2token):
    """Convert list[int] -> list[str]."""
    return [reverse_mapping[i] for i in id_seq]

In [86]:
df['token_id'] = decode(df['token_id'])

In [7]:
df_ch_only = df.loc[df['label']==1]

In [8]:
df_ch_only

         orig_index  token_id  attribution_score  label  prediction_prob
1040         128052        24          -1.145429    1.0         0.733358
1041         128052        24          -9.655292    1.0         0.733358
1042         128052         2          -3.252165    1.0         0.733358
1043         128052         4          -0.232236    1.0         0.733358
1044         128052        36          -2.106662    1.0         0.733358
...             ...       ...                ...    ...              ...
2578280      127356         0           0.000000    1.0         0.161055
2578281      127356         0           0.000000    1.0         0.161055
2578282      127356         0           0.000000    1.0         0.161055
2578283      127356         0           0.000000    1.0         0.161055
2578284      127356         0           0.000000    1.0         0.161055

[188257 rows x 5 columns]

In [40]:
pred = df_ch_only['prediction_prob'].quantile(0.7)

In [41]:
sort_95 = df_ch_only.loc[df_ch_only['prediction_prob']>pred].sort_values('prediction_prob', ascending=False)

In [42]:
top_25 = sort_95[['orig_index','label','prediction_prob']].drop_duplicates()[:30]['orig_index']

In [43]:
sort_95[['orig_index','label','prediction_prob']].drop_duplicates()[:30]

         orig_index  label  prediction_prob
229477          792    1.0         0.991545
336150        85396    1.0         0.991532
1991452      127654    1.0         0.991417
769460        42526    1.0         0.991396
1819351      169558    1.0         0.991395
934811        86584    1.0         0.991378
1340916       44282    1.0         0.991378
613146        84985    1.0         0.991378
772758        86013    1.0         0.991377
2436894      128315    1.0         0.991373
2547938       42375    1.0         0.991347
28204        171647    1.0         0.991334
466224       129162    1.0         0.991334
247467        85861    1.0         0.991330
2312473      128674    1.0         0.991327
665044       169846    1.0         0.991315
625510       170865    1.0         0.991309
705870       171956    1.0         0.991300
1357321       84941    1.0         0.991298
1066714         381    1.0         0.991298
964657          592    1.0         0.991295
2194456      129876    1.0         0.991283
1001090      129440    1.0         0.991273
1447553       86876    1.0         0.991266
87236         85270    1.0         0.991264
577789         2886    1.0         0.991263
682030        87490    1.0         0.991262
1816526       85800    1.0         0.991241
889965        45188    1.0         0.991223
902927       129792    1.0         0.991216

# Discards

In [11]:
mahjong_tiles = [
    # Manzu (Characters)
    "1m", "2m", "3m", "4m", "5m", "6m", "7m", "8m", "9m",
    
    # Souzu (Bamboos)
    "1s", "2s", "3s", "4s", "5s", "6s", "7s", "8s", "9s",
    
    # Pinzu (Circles)
    "1p", "2p", "3p", "4p", "5p", "6p", "7p", "8p", "9p",
    
    # Winds
    "East", "South", "West", "North",
    
    # Dragons (Colors)
    "White", "Green", "Red"
]

In [12]:
wind_translate = {0:"East",1:"South",2:"West",3:"North"}
is_riichi_translate={0:"No",1:"Yes"}

In [14]:
def display_discards(discard_df):
    print(f'Hand number: {discard_df['orig_index'][0]}')

    wind = discard_df['token_id'][0] - 34
    
    print(f'Wind: {wind}, {round(discard_df['attribution_score'][0],4)}')

    seat = discard_df['token_id'][1] - 38
    
    print(f'Seat: {seat}, {round(discard_df['attribution_score'][1],4)}')
    
    is_riichi = discard_df['token_id'][2] - 44
    
    print(f'Is riichi: {is_riichi_translate[is_riichi]}, {round(discard_df['attribution_score'][2],4)}')

    dora_ind = discard_df['token_id'][3] - 46
    
    print(f'Dora Indicator: {mahjong_tiles[dora_ind]}, {round(discard_df['attribution_score'][3],4)}')
    
    for i, r in discard_df[4:].iterrows():
        print(f'{mahjong_tiles[int(r['token_id'])]}, {round(r['attribution_score'],4)}')
    print('---------------------------------------------')

In [15]:
def display_discards_no_grad(discard_df):
    print(f'Hand number: {discard_df['orig_index'][0]}')

    wind = discard_df['token_id'][0] - 34
    
    print(f'Wind: {wind}')

    seat = discard_df['token_id'][1] - 38
    
    print(f'Seat: {seat}')
    
    is_riichi = discard_df['token_id'][2] - 44
    
    print(f'Is riichi: {is_riichi_translate[is_riichi]}')

    dora_ind = discard_df['token_id'][3] - 46
    
    print(f'Dora Indicator: {mahjong_tiles[dora_ind]}')
    
    for i, r in discard_df[4:].iterrows():
        print(f'{mahjong_tiles[int(r['token_id'])]}')
    print('---------------------------------------------')

In [ ]:
for hand in top_25:
    display_discards(df.loc[df['orig_index'] == hand].copy().reset_index())

In [ ]:
for hand in top_25:
    display(df.loc[df['orig_index'] == hand].copy().reset_index())

# Updated Grads

In [87]:
df.loc[df['orig_index'] == 792]

        orig_index   token_id  attribution_score  label  prediction_prob
229452         792          S          -0.019763    1.0         0.991545
229453         792          S          -0.608080    1.0         0.991545
229454         792       WU20          -0.014820    1.0         0.991545
229455         792        1st           0.006444    1.0         0.991545
229456         792  no_riichi          -0.040281    1.0         0.991545
229457         792       0_OR          -0.014579    1.0         0.991545
229458         792     LNorth           0.188170    1.0         0.991545
229459         792     PNorth           0.453856    1.0         0.991545
229460         792     LSouth           0.072493    1.0         0.991545
229461         792       RRed           0.145388    1.0         0.991545
229462         792     ANorth           0.073599    1.0         0.991545
229463         792     LGreen           0.012754    1.0         0.991545
229464         792     PGreen          -0.034329    1.0         0.991545
229465         792     RWhite           0.035652    1.0         0.991545
229466         792        A9s           0.020926    1.0         0.991545
229467         792        P2s          -0.016610    1.0         0.991545
229468         792        R6m          -0.002967    1.0         0.991545
229469         792        L8s           0.016243    1.0         0.991545
229470         792        P5s           0.033162    1.0         0.991545
229471         792      REast           0.073474    1.0         0.991545
229472         792        P2s           0.030921    1.0         0.991545
229473         792     AGreen          -0.182253    1.0         0.991545
229474         792        L2s           0.018860    1.0         0.991545
229475         792     RWhite           0.005840    1.0         0.991545
229476         792     ASouth           0.019872    1.0         0.991545
229477         792       PRed          -0.062066    1.0         0.991545
229478         792        A3s          -0.021121    1.0         0.991545
229479         792      LWest          -0.003769    1.0         0.991545
229480         792        P6s           0.159844    1.0         0.991545
229481         792      REast           0.036007    1.0         0.991545
229482         792     LSouth           0.051525    1.0         0.991545
229483         792     LGreen           0.004267    1.0         0.991545
229484         792        P2m           0.029854    1.0         0.991545

# Greater Patterns

In [88]:
df

         orig_index   token_id  attribution_score  label  prediction_prob
0             20453          S          -0.304067    0.0         0.084188
1             20453          E          -6.350651    0.0         0.084188
2             20453     WOoA20          -1.930850    0.0         0.084188
3             20453        1st           0.176169    0.0         0.084188
4             20453  no_riichi          -0.272070    0.0         0.084188
...             ...        ...                ...    ...              ...
2579652       48765        L1m           0.311494    0.0         0.003410
2579653       48765        P2m           0.173270    0.0         0.003410
2579654       48765        P1p          -0.464339    0.0         0.003410
2579655       48765        A8m           0.059956    0.0         0.003410
2579656       48765      PEast          -2.728711    0.0         0.003410

[1204773 rows x 5 columns]

In [89]:
df[['token_id','attribution_score']].groupby('token_id').mean().reset_index().sort_values('attribution_score', ascending=False)

     token_id  attribution_score
49        P4p           0.509300
37      LEast           0.311645
27        L1m           0.284201
51        P6m           0.277938
19     ASouth           0.222464
21     AWhite           0.205184
38     LGreen           0.198467
53        P7p           0.188791
74     RWhite           0.174534
40       LRed           0.159660
14        A9m           0.158066
34        L9m           0.155667
1         1st           0.148607
30        L2s           0.147306
41     LSouth           0.142576
32        L8p           0.125632
52        P6s           0.122532
29        L2p           0.113722
33        L8s           0.079201
18     ANorth           0.070834
35        L9p           0.067966
72     RSouth           0.062503
25       DRed           0.053210
22        D2s           0.046036
50        P5s           0.042789
36        L9s           0.040462
66        R8p           0.022045
42      LWest           0.016626
47        P2p           0.004449
17     AGreen           0.003342
16        A9s           0.000910
12        A8m           0.000313
28        L1s          -0.001038
71       RRed          -0.009772
5         A2m          -0.015259
67        R9s          -0.020980
46        P2m          -0.036370
63        R2m          -0.037929
7         A3m          -0.038567
54        P8s          -0.050797
31        L6p          -0.067268
65        R7m          -0.080560
4         A1p          -0.082036
15        A9p          -0.094487
2        2_OR          -0.094635
6         A2s          -0.105684
24        D6m          -0.108206
0        0_OR          -0.110106
48        P2s          -0.112494
13        A8s          -0.119323
58     PGreen          -0.121815
68      REast          -0.128046
43        P1m          -0.130826
39     LNorth          -0.143770
69     RGreen          -0.150266
60       PRed          -0.173841
11        A7p          -0.176577
70     RNorth          -0.213000
20      AWest          -0.221064
64        R6m          -0.223815
3         3rd          -0.227176
78  no_riichi          -0.230717
10        A6s          -0.239088
55        P9p          -0.248055
9         A3s          -0.261714
8         A3p          -0.289504
73      RWest          -0.307873
62        R1p          -0.313241
44        P1p          -0.382852
57      PEast          -0.472832
45        P1s          -0.537840
56        P9s          -0.545478
23        D4m          -0.629462
77       WU20          -0.674982
61      PWest          -0.741820
59     PNorth          -0.903818
75          S          -1.136551
76     WOoA20          -1.432623
26          E          -2.292120

In [90]:
len(df['token_id'].unique())

79

In [63]:
plt.hist(df[['token_id','attribution_score']].groupby('token_id').get_group('P4s')['attribution_score'], bins=100)

KeyError: 'P4s'